/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dicerollsimulator;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author dwayn
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setAppIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfAmtOfRolls = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txfFreq1 = new javax.swing.JTextField();
        txfFreq2 = new javax.swing.JTextField();
        txfFreq3 = new javax.swing.JTextField();
        txfFreq4 = new javax.swing.JTextField();
        txfFreq5 = new javax.swing.JTextField();
        txfFreqTotal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txfFreq6 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txfFrac1 = new javax.swing.JTextField();
        txfFrac2 = new javax.swing.JTextField();
        txfFrac3 = new javax.swing.JTextField();
        txfFrac4 = new javax.swing.JTextField();
        txfFrac5 = new javax.swing.JTextField();
        txfFrac6 = new javax.swing.JTextField();
        txfPer1 = new javax.swing.JTextField();
        txfPer2 = new javax.swing.JTextField();
        txfPer3 = new javax.swing.JTextField();
        txfPer4 = new javax.swing.JTextField();
        txfPer5 = new javax.swing.JTextField();
        txfPer6 = new javax.swing.JTextField();
        txfDec1 = new javax.swing.JTextField();
        txfDec2 = new javax.swing.JTextField();
        txfDec3 = new javax.swing.JTextField();
        txfDec4 = new javax.swing.JTextField();
        txfDec5 = new javax.swing.JTextField();
        txfDec6 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DiceRollSimulator");
        setMinimumSize(new java.awt.Dimension(950, 600));
        setSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(80, 65, 54));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dice Roll Simulator");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A Dice Rolling Simulator");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("By Dwayne Crous");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Enter how many rolls you would like to simulate:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 50));

        txfAmtOfRolls.setBackground(new java.awt.Color(204, 204, 204));
        txfAmtOfRolls.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txfAmtOfRolls, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 320, 30));

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.setToolTipText("Clears all the boxes and calculations.");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 150, 30));

        btnProcess.setBackground(new java.awt.Color(204, 204, 204));
        btnProcess.setForeground(new java.awt.Color(0, 0, 0));
        btnProcess.setText("Process");
        btnProcess.setToolTipText("Starts the calculations");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 150, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Frequency");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("3");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Theoretical Probability");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Frequency");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Decimal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Relative");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Fraction");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Percentage");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Total");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("1/6");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("2");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("4");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("5");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("6");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Outcome");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("1");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("1/6");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("1/6");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 30, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("1/6");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, 20));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("1/6");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("1/6");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, -1));

        txfFreq1.setEditable(false);
        txfFreq1.setBackground(new java.awt.Color(204, 204, 204));
        txfFreq1.setForeground(new java.awt.Color(0, 0, 0));
        txfFreq1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFreq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 50, -1));

        txfFreq2.setEditable(false);
        txfFreq2.setBackground(new java.awt.Color(204, 204, 204));
        txfFreq2.setForeground(new java.awt.Color(0, 0, 0));
        txfFreq2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFreq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 50, -1));

        txfFreq3.setEditable(false);
        txfFreq3.setBackground(new java.awt.Color(204, 204, 204));
        txfFreq3.setForeground(new java.awt.Color(0, 0, 0));
        txfFreq3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFreq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 50, -1));

        txfFreq4.setEditable(false);
        txfFreq4.setBackground(new java.awt.Color(204, 204, 204));
        txfFreq4.setForeground(new java.awt.Color(0, 0, 0));
        txfFreq4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFreq4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 50, -1));

        txfFreq5.setEditable(false);
        txfFreq5.setBackground(new java.awt.Color(204, 204, 204));
        txfFreq5.setForeground(new java.awt.Color(0, 0, 0));
        txfFreq5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFreq5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 50, -1));

        txfFreqTotal.setEditable(false);
        txfFreqTotal.setBackground(new java.awt.Color(204, 204, 204));
        txfFreqTotal.setForeground(new java.awt.Color(0, 0, 0));
        txfFreqTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFreqTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 70, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 690, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 810, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 810, 10));

        txfFreq6.setEditable(false);
        txfFreq6.setBackground(new java.awt.Color(204, 204, 204));
        txfFreq6.setForeground(new java.awt.Color(0, 0, 0));
        txfFreq6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFreq6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 50, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 810, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 690, 10));

        txfFrac1.setEditable(false);
        txfFrac1.setBackground(new java.awt.Color(204, 204, 204));
        txfFrac1.setForeground(new java.awt.Color(0, 0, 0));
        txfFrac1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFrac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 50, -1));

        txfFrac2.setEditable(false);
        txfFrac2.setBackground(new java.awt.Color(204, 204, 204));
        txfFrac2.setForeground(new java.awt.Color(0, 0, 0));
        txfFrac2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFrac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 50, -1));

        txfFrac3.setEditable(false);
        txfFrac3.setBackground(new java.awt.Color(204, 204, 204));
        txfFrac3.setForeground(new java.awt.Color(0, 0, 0));
        txfFrac3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFrac3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 50, -1));

        txfFrac4.setEditable(false);
        txfFrac4.setBackground(new java.awt.Color(204, 204, 204));
        txfFrac4.setForeground(new java.awt.Color(0, 0, 0));
        txfFrac4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFrac4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 50, -1));

        txfFrac5.setEditable(false);
        txfFrac5.setBackground(new java.awt.Color(204, 204, 204));
        txfFrac5.setForeground(new java.awt.Color(0, 0, 0));
        txfFrac5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFrac5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 50, -1));

        txfFrac6.setEditable(false);
        txfFrac6.setBackground(new java.awt.Color(204, 204, 204));
        txfFrac6.setForeground(new java.awt.Color(0, 0, 0));
        txfFrac6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfFrac6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 50, -1));

        txfPer1.setEditable(false);
        txfPer1.setBackground(new java.awt.Color(204, 204, 204));
        txfPer1.setForeground(new java.awt.Color(0, 0, 0));
        txfPer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfPer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 50, -1));

        txfPer2.setEditable(false);
        txfPer2.setBackground(new java.awt.Color(204, 204, 204));
        txfPer2.setForeground(new java.awt.Color(0, 0, 0));
        txfPer2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfPer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 50, -1));

        txfPer3.setEditable(false);
        txfPer3.setBackground(new java.awt.Color(204, 204, 204));
        txfPer3.setForeground(new java.awt.Color(0, 0, 0));
        txfPer3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfPer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 50, -1));

        txfPer4.setEditable(false);
        txfPer4.setBackground(new java.awt.Color(204, 204, 204));
        txfPer4.setForeground(new java.awt.Color(0, 0, 0));
        txfPer4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfPer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 50, -1));

        txfPer5.setEditable(false);
        txfPer5.setBackground(new java.awt.Color(204, 204, 204));
        txfPer5.setForeground(new java.awt.Color(0, 0, 0));
        txfPer5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfPer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 50, -1));

        txfPer6.setEditable(false);
        txfPer6.setBackground(new java.awt.Color(204, 204, 204));
        txfPer6.setForeground(new java.awt.Color(0, 0, 0));
        txfPer6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfPer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 50, -1));

        txfDec1.setEditable(false);
        txfDec1.setBackground(new java.awt.Color(204, 204, 204));
        txfDec1.setForeground(new java.awt.Color(0, 0, 0));
        txfDec1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfDec1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 50, -1));

        txfDec2.setEditable(false);
        txfDec2.setBackground(new java.awt.Color(204, 204, 204));
        txfDec2.setForeground(new java.awt.Color(0, 0, 0));
        txfDec2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfDec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 50, -1));

        txfDec3.setEditable(false);
        txfDec3.setBackground(new java.awt.Color(204, 204, 204));
        txfDec3.setForeground(new java.awt.Color(0, 0, 0));
        txfDec3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfDec3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 50, -1));

        txfDec4.setEditable(false);
        txfDec4.setBackground(new java.awt.Color(204, 204, 204));
        txfDec4.setForeground(new java.awt.Color(0, 0, 0));
        txfDec4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfDec4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 50, -1));

        txfDec5.setEditable(false);
        txfDec5.setBackground(new java.awt.Color(204, 204, 204));
        txfDec5.setForeground(new java.awt.Color(0, 0, 0));
        txfDec5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfDec5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 50, -1));

        txfDec6.setEditable(false);
        txfDec6.setBackground(new java.awt.Color(204, 204, 204));
        txfDec6.setForeground(new java.awt.Color(0, 0, 0));
        txfDec6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txfDec6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 50, -1));

        jPanel3.setBackground(new java.awt.Color(80, 65, 54));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Dwayne Crous Development 2024");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel26)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 950, 50));

        jPanel2.setBackground(new java.awt.Color(164, 158, 141));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 950, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        JTextField[] amountFields = {txfFreq1, txfFreq2, txfFreq3, txfFreq4, txfFreq5, txfFreq6};
        JTextField[] fractionFields = {txfFrac1, txfFrac2, txfFrac3, txfFrac4, txfFrac5, txfFrac6};
        JTextField[] percentageFields = {txfPer1, txfPer2, txfPer3, txfPer4, txfPer5, txfPer6};
        JTextField[] decimalFields = {txfDec1, txfDec2, txfDec3, txfDec4, txfDec5, txfDec6};
        
        for (int i = 0; i < 6; i++) {
            amountFields[i].setText("");
            fractionFields[i].setText("");
            percentageFields[i].setText("");
            decimalFields[i].setText("");
            txfAmtOfRolls.setText("");
            txfFreqTotal.setText("");
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        JTextField[] amountFields = {txfFreq1, txfFreq2, txfFreq3, txfFreq4, txfFreq5, txfFreq6};
        JTextField[] fractionFields = {txfFrac1, txfFrac2, txfFrac3, txfFrac4, txfFrac5, txfFrac6};
        JTextField[] percentageFields = {txfPer1, txfPer2, txfPer3, txfPer4, txfPer5, txfPer6};
        JTextField[] decimalFields = {txfDec1, txfDec2, txfDec3, txfDec4, txfDec5, txfDec6};
        
        
        int numRolls = Integer.parseInt(txfAmtOfRolls.getText());
        
        txfFreqTotal.setText(""+numRolls);
        
        int[] frequencies = new int[6];
        String[] fractions = new String[6];
        
        for (int i = 0; i < numRolls; i++) {
            int randomValue = (int) (Math.random() * 6) + 1;
            frequencies[randomValue - 1]++;
        }
        
        for (int j = 0; j < 6; j++) {
            amountFields[j].setText(String.valueOf(frequencies[j]));
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    
    private void setAppIcon() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/Square71x71Logo.scale-100.png"));
        setIconImage(icon.getImage());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField txfAmtOfRolls;
    private javax.swing.JTextField txfDec1;
    private javax.swing.JTextField txfDec2;
    private javax.swing.JTextField txfDec3;
    private javax.swing.JTextField txfDec4;
    private javax.swing.JTextField txfDec5;
    private javax.swing.JTextField txfDec6;
    private javax.swing.JTextField txfFrac1;
    private javax.swing.JTextField txfFrac2;
    private javax.swing.JTextField txfFrac3;
    private javax.swing.JTextField txfFrac4;
    private javax.swing.JTextField txfFrac5;
    private javax.swing.JTextField txfFrac6;
    private javax.swing.JTextField txfFreq1;
    private javax.swing.JTextField txfFreq2;
    private javax.swing.JTextField txfFreq3;
    private javax.swing.JTextField txfFreq4;
    private javax.swing.JTextField txfFreq5;
    private javax.swing.JTextField txfFreq6;
    private javax.swing.JTextField txfFreqTotal;
    private javax.swing.JTextField txfPer1;
    private javax.swing.JTextField txfPer2;
    private javax.swing.JTextField txfPer3;
    private javax.swing.JTextField txfPer4;
    private javax.swing.JTextField txfPer5;
    private javax.swing.JTextField txfPer6;
    // End of variables declaration//GEN-END:variables
}
